# Generated by Django 3.2 on 2022-05-25 00:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_tax_service', '0002_statuspayable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payables',
            fields=[
                ('bar_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_tax_service.statuspayable')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_tax_service.servicetype')),
            ],
        ),
    ]
