# Generated by Django 3.2 on 2022-05-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_tax_service', '0003_payables'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
