# Generated by Django 3.2 on 2022-05-25 00:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_tax_service', '0004_methodtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_card', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('importe_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('method_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_tax_service.methodtransaction')),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_tax_service.payables')),
            ],
        ),
    ]
